type Student {
  id: ID!
  firstName: String!
  lastName: String!
  claimedFreeShirt: Boolean!
}

input NewStudentInput {
  firstName: String!
  lastName: String!
}

input UpdateStudentInput {
  firstName: String
  lastName: String
  claimedFreeShirt: Boolean
}

extend type Query {
  student(id: ID!): Student!
  students: [Student]!
}

extend type Mutation {
  newStudent(input: NewStudentInput!): Student!
  updateStudent(id: ID!, input: UpdateStudentInput!): Student!
  removeStudent(id: ID!): Student!
}
