enum Gender {
  MENS
  WOMENS
  ADULT
}

type Product {
  id: ID!
  name: String!
  brand: String
  color: String!
  category: String!
  gender: Gender
  material: String!
  price: Int!
  sizes: [String]!
  imageUrl: String!
  createdAt: String!
  notes: [String]
}

input NewProductInput {
  name: String!
  brand: String
  color: String!
  category: String!
  gender: String
  material: String!
  price: Int!
  sizes: [String]!
  imageUrl: String!
  notes: [String]
}

input UpdateProductInput {
  name: String
  brand: String
  color: String
  category: String
  gender: String
  material: String
  price: Int
  sizes: [String]
  imageUrl: String
  notes: [String]
}

type Query {
  products: [Product]!
  product(id: ID!): Product!
}

type Mutation {
  newProduct(input: NewProductInput!): Product!
  updateProduct(id: ID!, input: UpdateProductInput!): Product!
  removeProduct(id: ID!): Product!
}
