type Product {
  id: ID!
  productId: String!
  name: String!
  brand: String!
  color: String!
  category: String!
  gender: String!
  material: String!
  price: Int!
  sizes: [String]!
  imageUrl: String!
}

input NewProductInput {
  productId: String!
  name: String!
  brand: String!
  color: String!
  category: String!
  gender: String!
  material: String!
  price: Int!
  sizes: [String]!
  imageUrl: String!
}

type Query {
  products: [Product]!
}

type Mutation {
  newProduct(input: NewProductInput!): Product!
}
