type SuccessMessage {
  message: String
}

type User {
  id: ID!
  firstName: String!
  lastName: String!
  email: String!
  password: String!
}

input NewUserInput {
  firstName: String!
  lastName: String!
  email: String!
  password: String!
}

input LoginInput {
  email: String!
  password: String!
}

extend type Query {
  logout: SuccessMessage
  me: User
}

extend type Mutation {
  signup(input: NewUserInput): User!
  login(input: LoginInput!): User
}
